config_name: 'textual.yaml'
data_path: '../data'
module: badcm.textual
device: '0'
dataset: 'NUS-WIDE'
mlm_path: 'bert-base-uncased'
max_text_len: 40
max_candidate: 128
bad_thred: 0.90
semantic_thred: 0.2
backdoor:
  strategy: 'bert-attack' #poison strategy, choose from ['direct', 'bert-attack']
  mode: 'all' # choose from ['random', 'all', 'sentence']
  word: 'cf'
  sentence: 'This is a poisoned sentence.'
surrogate:
  model: 'CLIPTextFeatureExtractor'
  cfg:
    from_pretrain: 'openai/clip-vit-base-patch32'
    max_text_len: 40
enable_use: false
use_path: 'checkpoints/0-feature_extractor'  # universal sentence encoder
badcm: null
enable_tb: false
