config_name: 'textual.yaml'
data_path: '../data'
module: badcm.textual
device: '0'
dataset: 'NUS-WIDE'
mlm_path: 'bert-base-uncased'
max_text_len: 40
max_candidate: 24
bad_thred: 0.99
semantic_thred: 0.4
backdoor:
  strategy: 'bert-attack' #poison strategy, choose from ['direct', 'bert-attack']
  mode: 'all' # choose from ['random', 'all', 'sentence']
  word: 'cf'
  sentence: 'This is a poisoned sentence.'
surrogate:
  model: 'TextFeatureExtractor'
  cfg:
    weights: 'checkpoints/0-feature_extractor/text_encoder.ckpt'
    vocab_size: 30522
    num_layers: 12
    num_heads: 12
    hidden_size: 768
    mlp_ratio: 4
    max_text_len: 40
    drop_rate: 0.1
enable_use: false
use_path: 'checkpoints/0-feature_extractor'  # universal sentence encoder
badcm: null
enable_tb: false