config_name: 'visual.yaml'
data_path: '../data'
module: badcm.visual
phase: 'train'
checkpoint: null
dataset: 'NUS-WIDE'
image_size: 224
pattern_img:
  mode: 'blend'  # choose from ['patch', 'blend', 'solid']
  path: 'config/pattern.jpg'
  size: 224
surrogate:
  model: 'CLIPImageFeatureExtractor'
  cfg:
    from_pretrain: 'openai/clip-vit-base-patch32'
batch_size: 64
epochs: 200
enable_mask: 'default' # choose from ['default', 'none', 'random']
perturbation: true  # generate perturbation directly or poisoned image
epislon: 0.5
optim:
  optimizer: 'adam'
  lr: 0.00001
  betas: [0.5, 0.999]
loss:
  region: 10.0
  alpha: 0.05
  beta: 2.0
device: '0'
valid_interval: 10
sample_batch: 0  # -1 for disable sample images
trial_tag: '0'
badcm: null
enable_tb: true
